### ISSUE TITLE
Cannot find bootstrap-tour.css

### ISSUE THREAD

**Issue by aussiDavid** [tienle/bootstrap-tour-rails#10]
I am using rails 4.
I followed the instructions on the README.md and my app cannot find the css file (the javascript file is ok).

Not sure what's wrong.

Thanks,

**Comment by varg90** [comment]
I just fixed it with `*= require bootstrap-tour/bootstrap-tour`

**Comment by aussiDavid** [comment]
It worked. Thank you.
